dbfilename redis_queue.rdb
dir /Users/wahab/Desktop/Projects/arsostech/erp-system/arsostech-bench/config/pids
pidfile /Users/wahab/Desktop/Projects/arsostech/erp-system/arsostech-bench/config/pids/redis_queue.pid
bind 127.0.0.1
port 11000

aclfile /Users/wahab/Desktop/Projects/arsostech/erp-system/arsostech-bench/config/redis_queue.acl
